// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChannelResponse.proto

package com.mogo.xts.netty.protobuf;

public final class ChannelResponseProto {
  private ChannelResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChannelResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string requestId = 1;
    /**
     * <code>required string requestId = 1;</code>
     */
    boolean hasRequestId();
    /**
     * <code>required string requestId = 1;</code>
     */
    String getRequestId();
    /**
     * <code>required string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    // required string action = 2;
    /**
     * <code>required string action = 2;</code>
     */
    boolean hasAction();
    /**
     * <code>required string action = 2;</code>
     */
    String getAction();
    /**
     * <code>required string action = 2;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();

    // required string context = 3;
    /**
     * <code>required string context = 3;</code>
     */
    boolean hasContext();
    /**
     * <code>required string context = 3;</code>
     */
    String getContext();
    /**
     * <code>required string context = 3;</code>
     */
    com.google.protobuf.ByteString
        getContextBytes();

    // required string retMsg = 4;
    /**
     * <code>required string retMsg = 4;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>required string retMsg = 4;</code>
     */
    String getRetMsg();
    /**
     * <code>required string retMsg = 4;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();
  }
  /**
   * Protobuf type {@code netty.ChannelResponse}
   */
  public static final class ChannelResponse extends
      com.google.protobuf.GeneratedMessage
      implements ChannelResponseOrBuilder {
    // Use ChannelResponse.newBuilder() to construct.
    private ChannelResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChannelResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChannelResponse defaultInstance;
    public static ChannelResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ChannelResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChannelResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              requestId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              action_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              context_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              retMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChannelResponseProto.internal_static_netty_ChannelResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChannelResponseProto.internal_static_netty_ChannelResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChannelResponse.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ChannelResponse> PARSER =
        new com.google.protobuf.AbstractParser<ChannelResponse>() {
      public ChannelResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChannelResponse(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ChannelResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string requestId = 1;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private Object requestId_;
    /**
     * <code>required string requestId = 1;</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string requestId = 1;</code>
     */
    public String getRequestId() {
      Object ref = requestId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string action = 2;
    public static final int ACTION_FIELD_NUMBER = 2;
    private Object action_;
    /**
     * <code>required string action = 2;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string action = 2;</code>
     */
    public String getAction() {
      Object ref = action_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          action_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string action = 2;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string context = 3;
    public static final int CONTEXT_FIELD_NUMBER = 3;
    private Object context_;
    /**
     * <code>required string context = 3;</code>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string context = 3;</code>
     */
    public String getContext() {
      Object ref = context_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          context_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string context = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      Object ref = context_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string retMsg = 4;
    public static final int RETMSG_FIELD_NUMBER = 4;
    private Object retMsg_;
    /**
     * <code>required string retMsg = 4;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string retMsg = 4;</code>
     */
    public String getRetMsg() {
      Object ref = retMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string retMsg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      Object ref = retMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      requestId_ = "";
      action_ = "";
      context_ = "";
      retMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRetMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getActionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getContextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getRetMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getActionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getContextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRetMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ChannelResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChannelResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChannelResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChannelResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChannelResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ChannelResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ChannelResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ChannelResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ChannelResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ChannelResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ChannelResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.ChannelResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ChannelResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChannelResponseProto.internal_static_netty_ChannelResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChannelResponseProto.internal_static_netty_ChannelResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChannelResponse.class, Builder.class);
      }

      // Construct using com.mogo.xts.netty.protobuf.ChannelResponseProto.ChannelResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        retMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChannelResponseProto.internal_static_netty_ChannelResponse_descriptor;
      }

      public ChannelResponse getDefaultInstanceForType() {
        return ChannelResponse.getDefaultInstance();
      }

      public ChannelResponse build() {
        ChannelResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ChannelResponse buildPartial() {
        ChannelResponse result = new ChannelResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.context_ = context_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.retMsg_ = retMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChannelResponse) {
          return mergeFrom((ChannelResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChannelResponse other) {
        if (other == ChannelResponse.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          bitField0_ |= 0x00000001;
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.hasAction()) {
          bitField0_ |= 0x00000002;
          action_ = other.action_;
          onChanged();
        }
        if (other.hasContext()) {
          bitField0_ |= 0x00000004;
          context_ = other.context_;
          onChanged();
        }
        if (other.hasRetMsg()) {
          bitField0_ |= 0x00000008;
          retMsg_ = other.retMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestId()) {
          
          return false;
        }
        if (!hasAction()) {
          
          return false;
        }
        if (!hasContext()) {
          
          return false;
        }
        if (!hasRetMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ChannelResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ChannelResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string requestId = 1;
      private Object requestId_ = "";
      /**
       * <code>required string requestId = 1;</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string requestId = 1;</code>
       */
      public String getRequestId() {
        Object ref = requestId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string requestId = 1;</code>
       */
      public Builder setRequestId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string requestId = 1;</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>required string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }

      // required string action = 2;
      private Object action_ = "";
      /**
       * <code>required string action = 2;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string action = 2;</code>
       */
      public String getAction() {
        Object ref = action_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string action = 2;</code>
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string action = 2;</code>
       */
      public Builder setAction(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string action = 2;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>required string action = 2;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        action_ = value;
        onChanged();
        return this;
      }

      // required string context = 3;
      private Object context_ = "";
      /**
       * <code>required string context = 3;</code>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string context = 3;</code>
       */
      public String getContext() {
        Object ref = context_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          context_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string context = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContextBytes() {
        Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string context = 3;</code>
       */
      public Builder setContext(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 3;</code>
       */
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000004);
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 3;</code>
       */
      public Builder setContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        context_ = value;
        onChanged();
        return this;
      }

      // required string retMsg = 4;
      private Object retMsg_ = "";
      /**
       * <code>required string retMsg = 4;</code>
       */
      public boolean hasRetMsg() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string retMsg = 4;</code>
       */
      public String getRetMsg() {
        Object ref = retMsg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          retMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string retMsg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string retMsg = 4;</code>
       */
      public Builder setRetMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        retMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string retMsg = 4;</code>
       */
      public Builder clearRetMsg() {
        bitField0_ = (bitField0_ & ~0x00000008);
        retMsg_ = getDefaultInstance().getRetMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string retMsg = 4;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        retMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netty.ChannelResponse)
    }

    static {
      defaultInstance = new ChannelResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netty.ChannelResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_ChannelResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_ChannelResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025ChannelResponse.proto\022\005netty\"U\n\017Channe" +
      "lResponse\022\021\n\trequestId\030\001 \002(\t\022\016\n\006action\030\002" +
      " \002(\t\022\017\n\007context\030\003 \002(\t\022\016\n\006retMsg\030\004 \002(\tB3\n" +
      "\033com.mogo.xts.netty.protobufB\024ChannelRes" +
      "ponseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_netty_ChannelResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_netty_ChannelResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_netty_ChannelResponse_descriptor,
              new String[] { "RequestId", "Action", "Context", "RetMsg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
